language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm i -g mocha
- npm install
script:
- npm run test
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 39.108.170.7
after_success:
- chmod 600 ~/.ssh/jianshu
- echo -e "User root\n\tHost jianshu\n\tHostName 39.108.170.7\n\tPort 22\n\tIdentityFile
  ~/.ssh/jianshu\n\tProtocol 2\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 644 ~/.ssh/config
- ssh jianshu 'cd /home/wwwroot/ && touch travis_test_ok'
before_install:
- openssl aes-256-cbc -K $encrypted_4cf349d53060_key -iv $encrypted_4cf349d53060_iv
  -in jianshu.enc -out ~/.ssh/jianshu -d
