language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm i -g mocha
- npm install
script:
- npm run test
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 47.100.187.149
before_install:
- openssl aes-256-cbc -K $encrypted_afb3f4a0fd37_key -iv $encrypted_afb3f4a0fd37_iv
  -in ezcp_rsa.enc -out ~/.ssh/ezcp_rsa -d
after_success:
- chmod 600 ~/.ssh/ezcp_rsa
- cat ~/.ssh/ezcp_rsa
- echo -e "User root\n\tHost ezcp\n\tHostName 47.100.187.149\n\tPort 22\n\tIdentityFile
  ~/.ssh/ezcp_rsa\n\tProtocol 2\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 644 ~/.ssh/config
- scp -r ./** ezcp:/usr/src/travis
- ssh ezcp 'cd /usr/src/travis && npm install --production && npm start'
